/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Header: typeof import('./src/components/Header/index.vue')['default'];
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    Layout: typeof import('./src/components/Layout/index.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VanButton: typeof import('vant/es')['Button'];
  }
}
